name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform:
        - os: ubuntu-latest
      fail-fast: false

    runs-on: ${{ matrix.platform.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: install deps
        run: |
          sudo apt-get install -y kcov || true
          sudo apt-get install -y tree || true

      - name: Run Tests
        run: COV=1 bash test/run.sh
